version: "3.9"
services:
  db:
    container_name: blog-app-db
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: note_app
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - .db//mysql/sql:/docker-entrypoint-initdb.d
volumes:
  db_data: