mutation CreateUser(
  $userId: String!
  $username: String!
  $displayname: String!
) {
  createUser(userId: $userId, username: $username, displayname: $displayname) {
    userId
    username
    displayname
  }
}
