name: Lint and Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run lint
        run: |
          cd backend
          npm run lint
          npm run format

      - name: Run Jest tests
        run: |
          cd backend
          npm run test
